name: formz_inputs
description: Text input field state helpers extending felangel `formz` package...
version: 0.0.1
author: s

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  formz: ^0.4.0

dev_dependencies:
  test: ^1.17.4
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
