name: product_repository
description: Repository to manage static file product info
version: 0.0.1
author: "sl"
homepage: "https://github.com/portal-webstore/fiery_flutter_prototype_archi"
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  drug_repository:
    path: ../drug_repository
  equatable: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
