name: boundary_data_transducer
description: Conversion helpers parsing data from relatively untrusted sources
version: 0.0.1
author: s

environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  test: ^1.17.4
