name: patient_repository
description: Patient repository for clinic's patients.
version: 0.0.1
author: s
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  i18n_l10n_australian:
    path: "../i18n_l10n_australian"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
