name: order_repository
description: A new Flutter package project.
version: 0.0.1
author: "sl"
homepage: "https://github.com/portal-webstore/fiery_flutter_prototype_archi"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
